services:

  php84:
    build:
      args:
        PHP_VERSION: 8.4

  php83:
    build:
      args:
        PHP_VERSION: 8.3

  php82:
    build:
      args:
        PHP_VERSION: 8.2

  php81:
    build:
      args:
        PHP_VERSION: 8.1
